"""empty message

Revision ID: 2649da7cba26
Revises: None
Create Date: 2014-11-16 12:07:17.006864

"""

# revision identifiers, used by Alembic.
revision = '2649da7cba26'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
